[project]
name = "spm-workspace"
version = "0.1.0"
description = "Slang package manager"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "spm",
    "spm-test",
    "package-a",
    "package-b",
    "package-c",
    "package-e",
    "package-f",
]

[tool.uv.workspace]
members = ["libs/*", "tests/*"]

[tool.uv.sources]
spm = { workspace = true }
spm-test = { workspace = true }
package-a = { workspace = true }
package-b = { workspace = true }
package-c = { workspace = true }
package-e = { workspace = true }
package-f = { workspace = true }

[dependency-groups]
dev = [
    "black>=26.3.1",
    "build>=1.4.3",
    "pytest>=9.0.3",
    "twine>=6.2.0",
]
